require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CurrencyPairsController do

  # This should return the minimal set of attributes required to create a valid
  # CurrencyPair. As you add validations to CurrencyPair, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CurrencyPairsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all currency_pairs as @currency_pairs" do
      currency_pair = CurrencyPair.create! valid_attributes
      get :index, {}, valid_session
      assigns(:currency_pairs).should eq([currency_pair])
    end
  end

  describe "GET show" do
    it "assigns the requested currency_pair as @currency_pair" do
      currency_pair = CurrencyPair.create! valid_attributes
      get :show, {:id => currency_pair.to_param}, valid_session
      assigns(:currency_pair).should eq(currency_pair)
    end
  end

  describe "GET new" do
    it "assigns a new currency_pair as @currency_pair" do
      get :new, {}, valid_session
      assigns(:currency_pair).should be_a_new(CurrencyPair)
    end
  end

  describe "GET edit" do
    it "assigns the requested currency_pair as @currency_pair" do
      currency_pair = CurrencyPair.create! valid_attributes
      get :edit, {:id => currency_pair.to_param}, valid_session
      assigns(:currency_pair).should eq(currency_pair)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CurrencyPair" do
        expect {
          post :create, {:currency_pair => valid_attributes}, valid_session
        }.to change(CurrencyPair, :count).by(1)
      end

      it "assigns a newly created currency_pair as @currency_pair" do
        post :create, {:currency_pair => valid_attributes}, valid_session
        assigns(:currency_pair).should be_a(CurrencyPair)
        assigns(:currency_pair).should be_persisted
      end

      it "redirects to the created currency_pair" do
        post :create, {:currency_pair => valid_attributes}, valid_session
        response.should redirect_to(CurrencyPair.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved currency_pair as @currency_pair" do
        # Trigger the behavior that occurs when invalid params are submitted
        CurrencyPair.any_instance.stub(:save).and_return(false)
        post :create, {:currency_pair => {  }}, valid_session
        assigns(:currency_pair).should be_a_new(CurrencyPair)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        CurrencyPair.any_instance.stub(:save).and_return(false)
        post :create, {:currency_pair => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested currency_pair" do
        currency_pair = CurrencyPair.create! valid_attributes
        # Assuming there are no other currency_pairs in the database, this
        # specifies that the CurrencyPair created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        CurrencyPair.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => currency_pair.to_param, :currency_pair => { "these" => "params" }}, valid_session
      end

      it "assigns the requested currency_pair as @currency_pair" do
        currency_pair = CurrencyPair.create! valid_attributes
        put :update, {:id => currency_pair.to_param, :currency_pair => valid_attributes}, valid_session
        assigns(:currency_pair).should eq(currency_pair)
      end

      it "redirects to the currency_pair" do
        currency_pair = CurrencyPair.create! valid_attributes
        put :update, {:id => currency_pair.to_param, :currency_pair => valid_attributes}, valid_session
        response.should redirect_to(currency_pair)
      end
    end

    describe "with invalid params" do
      it "assigns the currency_pair as @currency_pair" do
        currency_pair = CurrencyPair.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CurrencyPair.any_instance.stub(:save).and_return(false)
        put :update, {:id => currency_pair.to_param, :currency_pair => {  }}, valid_session
        assigns(:currency_pair).should eq(currency_pair)
      end

      it "re-renders the 'edit' template" do
        currency_pair = CurrencyPair.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CurrencyPair.any_instance.stub(:save).and_return(false)
        put :update, {:id => currency_pair.to_param, :currency_pair => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested currency_pair" do
      currency_pair = CurrencyPair.create! valid_attributes
      expect {
        delete :destroy, {:id => currency_pair.to_param}, valid_session
      }.to change(CurrencyPair, :count).by(-1)
    end

    it "redirects to the currency_pairs list" do
      currency_pair = CurrencyPair.create! valid_attributes
      delete :destroy, {:id => currency_pair.to_param}, valid_session
      response.should redirect_to(currency_pairs_url)
    end
  end

end
